import Footer from "@/components/Footer"
import Head from "next/head"
import Link from "next/link"
import { useState } from "react"
import { addCampaign, getLastCampaignId } from "@/service/Web3Service"

export default function CreateCampaign(){
    const [campaign, setCampaign] = useState({})
    const [message, setMessage] = useState("")

    function onInputChange(e){
        setCampaign(prevState => ({...prevState, [e.target.id] : e.target.value}))
    }

    function btnSaveClick(){
        // alert(JSON.stringify(campaign));
        setMessage("Saving...loading...wait")
        addCampaign(campaign)
            .then(tx => getLastCampaignId())
            .then(id => setMessage(`Campaign saved with ID ${id}. Tell your friends and send for them this number.`))
            .catch(err =>{
                console.error(err);
                setMessage(err.message)
            })
    }

    return (
        <>
            <Head>
                <title>Donate Crypto | Create Campaign</title>
                <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            </Head>
            <div className="container">
                <h1 className="display-5 fw-bold text-body-emphasis lh-1 mb-3">Donate Crypto</h1>
                <p>Preencha os campos para incluir sua campanha na plataforma.</p>
                <hr className="mb-4"/>
                <div className="col-6">
                    <div className="form-floating mb-3">
                        <input type="text" id="title" className="form-control" value={campaign.title} onChange={onInputChange} />
                        <label htmlFor="title">Title:</label>
                    </div>
                    <div className="form-floating mb-3">
                        <input type="text" id="description" className="form-control"  value={campaign.description} onChange={onInputChange} />
                        <label htmlFor="description">Description:</label>
                    </div>
                    <div className="form-floating mb-3">
                    <input type="text" id="url_image" className="form-control" value={campaign.url_image} onChange={onInputChange} />
                        <label htmlFor="url_image">URL Image:</label>
                    </div>
                    <div className="form-floating mb-3">
                        <input type="text" id="url_video" className="form-control" value={campaign.url_video} onChange={onInputChange} />
                        <label htmlFor="url_video">URL Video:</label>
                    </div>
                </div>
                <div className="col-6 mb-3">
                    <input type="button" value="Save" className="btn btn-primary col-12 p-3" onClick={btnSaveClick}/>
                </div>
                <div className="col-6 mb-3">
                    <Link href="/" className="btn btn-secondary col-12 p-3">Back</Link>
                </div>
                {
                    message?
                    <div className="alert alert-success p-3 col-6" role="alert">{message}</div>
                    :<></>
                }
                <Footer/>
            </div>     
        </>
    )
}