import Footer from "@/components/Footer"
import Head from "next/head"
import Link from "next/link"
import { useState } from "react"
import { getCampaign, donate } from "@/service/Web3Service"

export default function Donate(){
    const [campaign, setCampaign] = useState({})
    const [donation, setDonation] = useState(0)
    const [message, setMessage] = useState("")

    function onChangeId(e){
        campaign.id = e.target.value;
    }

    function btnSearchClick(){
        // alert(JSON.stringify(campaign));
        
        setMessage("Searching...loading...wait")
        getCampaign(campaign.id)
            .then(result => {
                setMessage("");
                result.id = campaign.id;
                setCampaign(result)
            }).catch(err =>setMessage(err.message))
    }

    function onChangeValue(e){
        setDonation(e.target.value)
    }

    function btnDonateClick(){
        setMessage("Donated...wait...")
        donate(campaign.id, donation)
            .then(tx => {
                setMessage(`Donation made, thank you. In a few minutes, the balance will be updated.`);
            }).catch(err =>setMessage(err.message))
    }

    return (
        <>
            <Head>
                <title>Donate Crypto | To make Campaign</title>
                <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            </Head>
            <div className="container">
                <h1 className="display-5 fw-bold text-body-emphasis lh-1 mb-3">Donate Crypto</h1>
                {
                    !campaign.id?
                    (
                        <>
                        <p className="mb-5">Qual é o ID da campanha que procura?</p>
                        <div className="col-3">
                            <div className="input-group mb-3">
                                <input type="number" min={1} id="campaignId" className="form-control" value={campaign.id} onChange={onChangeId}/>
                                <input type="button" value="Search" className="btn btn-primary p-3" onClick={btnSearchClick}/>
                            </div>
                        </div>
                        </>
                    ):(
                        <>
                        <p>Verifique se esta é a campanha correta antes de fazer a doação.</p>
                        <hr/>
                        <div className="row flex-lg-row-reverse align-items-center py-5 g-5">
                            <div className="col-7">
                                {
                                    // JSON.stringify(campaign)
                                    campaign.videoUrl?
                                    <iframe width="100%" height="480" src={campaign.videoUrl}></iframe>
                                    :<img src={campaign.imageUrl} className="d-block mx-lg-auto img-fluid" width="100%" height="480" />
                                    
                                }
                            </div>
                            <div className="col-5 mb-5" style={{height: 480, scrollbars: true}}>
                                <h2>{campaign.title}</h2>
                                <p><strong>Autor:</strong>{campaign.author}</p>
                                <p className="mb-3">{campaign.description}</p>
                                {
                                    campaign.videoUrl?
                                    <p>Assista o vídeo ao lado para entender mais sobre a campanha</p>
                                    :<></>
                                }
                                <p className="mb-3 fst-italic mt-5">E aí, o que achou do projeto? Ja foi arrecadado {campaign.balance / 10 ** 18} BNB. Quanto deseja doar para esta campanha?</p>
                                <div className="mb-3">
                                    <div className="input-group">
                                        <input type="number" min={1} id="donation" className="form-control p-3" value={donation} onChange={onChangeValue}/>
                                        <span className="input-group-text">BNB</span>
                                        <input type="button" value="Donate" className="btn btn-primary p-3 w-25" onClick={btnDonateClick}/>
                                    </div>
                                </div>
                            </div>
                        </div>
                        </>
                    )
                }
                
                <div className="col-6 mb-3">
                    <Link href="/" className="btn btn-secondary p-3">Back</Link>
                </div>
                {
                    message?
                    <div className="alert alert-success p-3 col-6" role="alert">{message}</div>
                    :<></>
                }
                <Footer/>
            </div>     
        </>
    )
}